apiVersion: sources.eventing.triggermesh.dev/v1alpha1
kind: VSphereSource
metadata:
  name: vsphere-sample-source
spec:
  vsphereCredsSecret:
    name: vsphere-credentials
    key: password
  vsphereUser: <vSphere username>
  vsphereUrl: <vSphere domain or IP>
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: event-display
